name: myenv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - streamlit
  - pip
  - pip:
      - hafez
      - pyyaml
      - ua-parser
      - user-agents
